---
title: "Assignment 3"
author: "Xiangyu Ma"
date: "10/28/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(ipumsr) # this ipum package needs to be installed
```

# Variables to include:

stateicp & statefip
perwt
age
sex
nchild
educd
school
race
hispan
met2013
wkswork2
uhrswork
wrklstwk
incwage
incearn

```{r}
# load data
ddi <- read_ipums_ddi("usa_00001.xml")
df <- read_ipums_micro(ddi)
```


```{r}
# recode race into 4 categories, as xy_race
df <- mutate(df, xy_race = if_else(RACE == 1, "White", 
                                   if_else(RACE == 2, "Black",
                                           if_else(RACE >3 & RACE < 7, "Asian", "Other")))) 

# recode hispanic into binary variable, xy_hisp
df <- mutate(df, xy_hisp = if_else(HISPAN == 0, 0, 1))

# recode met2013 into a binary varible, xy_met
df <- mutate(df, xy_met = if_else(MET2013 == 0, 0, 1))

# recode a bunch of dummy variables for education
df <- mutate(df, less_hs = if_else(EDUCD < 30, 1, 0)) %>%
  mutate(some_hs = if_else(EDUCD >= 30 & EDUCD < 60, 1, 0)) %>%
  mutate(ged = if_else(EDUCD == 64, 1, 0)) %>%
  mutate(hs_grad = if_else(EDUCD == 63, 1, 0)) %>%
  mutate(some_col = if_else((EDUCD > 64 & EDUCD < 81), 1, 
    if_else(EDUCD == 90, 1, 
        if_else(EDUCD == 100, 1, 
            if_else(EDUCD >= 110 & EDUC < 114, 1, 0))))) %>%
  mutate(assoc_deg = if_else(EDUCD > 80 & EDUC <90, 1, 0)) %>%
  mutate(bach = if_else(EDUCD == 101, 1, 0)) %>%
  mutate(masters = if_else(EDUCD == 114, 1, 0)) %>%
  mutate(profd = if_else(EDUCD == 115, 1, 0)) %>%
  mutate(phd = if_else(EDUCD == 116, 1, 0))
```

# Question 1

```{r}

```












